Modularize: Minor PR
grantmcdermott/tinyplot pull request #214
Opened 2024-09-09 01:57 UTC by vincentarelbundock

A minor PR with some more modularization/simplification:

* Removed duplicated code
* Removed unused arguments
* `type_*()` data preparation function are now stored in a dictionary with switch-style selection.

2024-09-10 04:41 UTC, grantmcdermott requested changes
Very nice, thanks. One minor comment and then happy to merge.

2024-09-10 04:41 UTC, grantmcdermott commented on R/by_aesthetics.R
> +  if (is.null(bg) && !is.null(fill)) bg = fill
Should this go higher up in the main tinyplot function? That way, we can also drop the extra fill argument for this `by_bg` function (as well as the input on l. 665 below).

2024-09-10 23:59 UTC, grantmcdermott approved these changes

2024-09-10 23:59 UTC, merged

2024-09-11 00:00 UTC, grantmcdermott commented
Not so minor in the end... thanks again for the continued efficiency gains!

2024-09-11 00:14 UTC, vincentarelbundock commented
no it really was minor. I just noticed that your suggestion could help us simplify something else too.

This was a simple PR, but I'll take the 35 lines of code removed :)