Pass type arguments through dots
grantmcdermott/tinyplot pull request #267
Opened 2024-11-23 00:38 UTC by zeileis

Today I took a quick stab at passing arguments through the dots `...` to the `type_*` function. The main motivation for this came from https://github.com/grantmcdermott/tinyplot/pull/233#issuecomment-2443010778. Because:

```
plot(Species ~ Sepal.Width, data = iris, breaks = 4)
```

works, I also wanted to get

```
tinyplot(Species ~ Sepal.Width, data = iris, breaks = 4)
```

to work rather than having to call

```
tinyplot(Species ~ Sepal.Width, data = iris, type = type_spineplot(breaks = 4))
```

Similarly, instead of

```
plot(count ~ spray, data = InsectSprays, lty = 1, staplewex = 0)
```

we can now also do

```
tinyplot(count ~ spray, data = InsectSprays, lty = 1, staplewex = 0)
```

rather than having to use

```
tinyplot(count ~ spray, data = InsectSprays, lty = 1, type = type_boxplot(staplewex = 0))
```

![tinyplot-dots](https://github.com/user-attachments/assets/4a1ab54b-ccc9-4574-9054-423d7e19dd85)

I've implemented this by:

- Passing the `dots` also to `sanitize_type`.
- Obtaining the `type` function without evaluating it yet.
- Taking those named arguments from `dots` that match arguments of `type` using them to evaluate `type`.
- Returning the remainings `dots` back to the `tinyplot`.

Thus, this only works for `type` arguments that are not arguments of `tinyplot` \_and\_ do not even partially match! So this is a potential source of confusion. But it does avoid the potential confusion from examples like the ones above.

2024-11-23 01:00 UTC, vincentarelbundock commented
This seems pretty straightforward and useful. 

We may still want to strictly advertise the "old" system on the website and in the docs, because it clearly indicates where users should look for to get documentation on type-specific arguments. 

Perhaps showing a call-out box with a "tip" about `...`, while staying ultra consistent throughout the website. 

Not quite the "there should be only one way" Tao, but...

2024-11-23 01:36 UTC, zeileis commented
I've now also added `"function"` to the official `types` in `sanitize_type()` now. It does not strictly belong to this PR but I thought that it fits sufficiently well and it's only a minor edit.

2024-11-25 00:39 UTC, vincentarelbundock commented
I've looked at the code and don't see any problem. Do you plan to do more work on this? If not, I think we should just merge it.

2024-11-25 00:45 UTC, zeileis commented
Great, thanks for the feedback, Vincent. I also don't think that further work is needed. So let's see whether Grant @grantmcdermott has any concerns...

2024-11-25 22:05 UTC, grantmcdermott requested changes
Thanks Achim. I agree that this is helpful and adds a disciplined "backend" for users that would like to pass customization arguments without having to go through the `type_*()` functions.

On that note, we'll also need to edit the first "breaking changes" item in NEWS here. https://github.com/grantmcdermott/tinyplot/blob/d76f4f1cd5adc1155a1160eb6a3dc815dc3245e8/NEWS.md?plain=1#L9-L25
Do you mind taking a crack at the re-wording? We can obviously move it out of breaking changes, since the old way will work again with your PR. But we should underscore that the documentation lives with the individual type functions and politely suggest that passing arguments through them (rather than `...`) is the more idiomatic tinyplot way of doing things now.

2024-11-26 07:48 UTC, zeileis commented on R/sanitize.R
>    )
I have rephrased/reorganized the NEWS. Please have a look at whether you like this approach or would prefer to do it differently. Maybe there should also be something in the vignette?

I also noticed that there is still a mentioning of `ribbon.apha` in `tinyplot.Rd` which can probably go.

I fully agree with the other proposed changes and will do them a bit later...

2024-11-26 17:34 UTC, grantmcdermott commented on R/sanitize.R
>    )
> I also noticed that there is still a mentioning of `ribbon.apha` in `tinyplot.Rd` which can probably go.

Good catch! Yes, please remove.

2024-11-26 21:55 UTC, zeileis commented on R/sanitize.R
>    )
All done. Please check the NEWS update to see whether you like it - and whether you agree that the non-standard spacing is helpful in https://github.com/grantmcdermott/tinyplot/blob/type-dots/R/sanitize.R#L36-L64

Open: Add something in vignette? Add tests, e.g., checking that `tinyplot(Nile, type = "hist", breaks  30)` is indeed identical to `tinyplot(Nile, type = type_hist(breaks = 30))`?

2024-11-27 05:10 UTC, merged

2024-11-27 05:10 UTC, grantmcdermott commented
Great stuff, thanks @zeileis!